version: '3.9'
services:
  app:
    container_name: env-test
    image: section-compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Application__UrlHost=http://fake.host/get
      - Storage__ConnectionString=ConnectionString
      - Storage__ContainerName=ContainerName
      - Array__0__Value=One
      - Array__1__Value=Two
    ports:
      - "5001:80"